[package]
name = "db_proc_macros"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
#syn = "0.11.11"
syn = "0.12.13"
quote = "0.4.2"
#quote = "0.3.15"